name: Deploy Backend to Azure Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend (Azure Functions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create deployment package
        run: |
          # Remove node_modules and create clean package
          rm -rf node_modules
          npm ci --production
          zip -r deploy.zip . -x "*.git*" "*node_modules/.cache*" "*.github*"
      
      - name: Deploy to Azure Functions
        uses: azure/CLI@v1
        with:
          azcli-version: 2.30.0
          inlineScript: |
            az functionapp deployment source config-zip \
              --resource-group TutorAleman-RG-v2 \
              --name tutor-aleman-backend-v4 \
              --src deploy.zip
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Verify Backend Deployment
        run: |
          sleep 30
          curl -f "https://tutor-aleman-backend-v4.azurewebsites.net/api/hello" && echo "✅ Backend updated!" || echo "❌ Backend not updated"