name: Deploy Frontend Only

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend (Azure Static Web Apps)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: ""
      
      - name: Verify Frontend Deployment
        run: |
          sleep 30
          curl -f "https://proud-plant-03fdf9603.1.azurestaticapps.net/" | grep -q "Conversación Continua con Memoria" && echo "✅ Frontend updated!" || echo "❌ Frontend not updated"