name: Deploy Backend to Azure Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend (Azure Functions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'tutor-aleman-backend-v4'
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_V4 }}
      
      - name: Verify Backend Deployment
        run: |
          sleep 30
          curl -f "https://tutor-aleman-backend-v4.azurewebsites.net/api/hello" && echo "✅ Backend updated!" || echo "❌ Backend not updated"