name: Manual Force Deploy (Emergency)

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'What to deploy'
        required: true
        default: 'both'
        type: choice
        options:
        - backend
        - frontend
        - both

jobs:
  force-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js (if deploying backend)
        if: ${{ github.event.inputs.component == 'backend' || github.event.inputs.component == 'both' }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies (if deploying backend)
        if: ${{ github.event.inputs.component == 'backend' || github.event.inputs.component == 'both' }}
        run: npm ci
      
      - name: Deploy Backend
        if: ${{ github.event.inputs.component == 'backend' || github.event.inputs.component == 'both' }}
        uses: Azure/functions-action@v1
        with:
          app-name: 'tutor-aleman-backend-v4'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      
      - name: Deploy Frontend
        if: ${{ github.event.inputs.component == 'frontend' || github.event.inputs.component == 'both' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: ""